# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fplassist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fpl_config',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
