# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fplassist', '0002_auto_20171020_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_basic_stats',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='player_basic_stats',
            name='form',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='player_basic_stats',
            name='ppg',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='player_basic_stats',
            name='tsb',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='player_detailed_stats',
            name='ict_index',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='team_info',
            name='fixture_difficulty',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
