# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 19:28
from __future__ import unicode_literals

from decimal import Decimal
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fplassist', '0002_player_info_player_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_detailed_stats',
            name='ict_history',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4), default=list, size=38),
        ),
        migrations.AddField(
            model_name='player_detailed_stats',
            name='points_history',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), default=list, size=38),
        ),
    ]
