# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 21:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fplassist', '0003_auto_20171020_0222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player_info',
            name='squad_number',
        ),
    ]
