# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fplassist', '0004_remove_player_info_squad_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_basic_stats',
            name='cost',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='player_basic_stats',
            name='form',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='player_basic_stats',
            name='ppg',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='player_basic_stats',
            name='tsb',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='player_detailed_stats',
            name='ict_index',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='team_info',
            name='fixture_difficulty',
            field=models.IntegerField(default=4),
        ),
    ]
