# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-05 11:26
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.IntegerField(default=0)),
                ('boxoffice', models.IntegerField(default=0)),
                ('imdb', models.IntegerField(default=0)),
                ('metacritic', models.IntegerField(default=0)),
                ('rottentomatoes', models.IntegerField(default=0)),
                ('genre', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), default=list, size=50)),
                ('director', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), default=list, size=50)),
                ('lang', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), default=list, size=50)),
                ('country', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), default=list, size=50)),
                ('prod', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), default=list, size=50)),
            ],
        ),
    ]
