# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 19:14
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviecritic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_details',
            name='boxoffice',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movie_details',
            name='country',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=35), default=list, size=50),
        ),
        migrations.AlterField(
            model_name='movie_details',
            name='director',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=35), default=list, size=50),
        ),
        migrations.AlterField(
            model_name='movie_details',
            name='genre',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=list, size=50),
        ),
        migrations.AlterField(
            model_name='movie_details',
            name='lang',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=list, size=50),
        ),
        migrations.AlterField(
            model_name='movie_details',
            name='prod',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), default=list, size=50),
        ),
    ]
