# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 19:29
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviecritic', '0002_auto_20171108_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_details',
            name='country',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), default=list, size=50),
        ),
        migrations.AlterField(
            model_name='movie_details',
            name='director',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), default=list, size=50),
        ),
        migrations.AlterField(
            model_name='movie_details',
            name='genre',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), default=list, size=50),
        ),
        migrations.AlterField(
            model_name='movie_details',
            name='lang',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), default=list, size=50),
        ),
    ]
